openapi: 3.0.3
info:
  title: DB Connection Service API
  description: API of the database connection service.
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /report:
    get:
      summary: Standard Query
      description: Queries the database with pre-specified input. Used to get the standard data used by monthly reports. Returns Array structured data.
      parameters:
        - in: header
          name: month
          schema:
            type: string
          description: Specifies which monthly data is retrieved(YYYY-MM). Date can't be in the future.
      responses:
        200:
          description: Successful query response with standard data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  withdrawals:
                    type: array
                    items:
                      type: object
                      properties:
                        withdrawalId:
                          type: string
                          description: Id of the withdrawal
                        member:
                          type: string
                          description: Name of the Member that withdrew
                        time:
                          type: date
                          description: Time of withdrawal
                        amount:
                          type: integer
                          description: Amount withdrawn
                    description: All withdrawals of the specified month
                  totalAmount:
                    type: integer
                    description: Total amount of cannabis withdrawal in specified month
                  memberCount:
                    type: integer
                    description: Total amount of members right now
                  avgPerMember:
                    type: array
                    items:
                      type: object
                      properties:
                        member:
                          type: string
                          description: Name of member
                        average:
                          type: integer
                          description: Average amount withdrawn by this member
                    description: All members and their average withdrawal

        400:
          description: Query lacks sufficient query parameter (Month specification).
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid month specified"
        500:
          description: Internal server error occurred
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error occurred"