openapi: 3.0.3
info:
  title: DB Connection Service API
  description: API of the database connection service.
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /report:
    get:
      summary: Standard Query
      description: Queries the database with pre-specified input. Used to get the standard data used by monthly reports. Returns Array structured data.
      parameters:
        - in: query
          name: month
          schema:
            type: string
          description: Specifies which monthly data is retrieved.
      responses:
        200:
          description: Successful query response with standard data.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    monthlyWithdrawal:
                      type: integer
                      description: Total cannabis withdraw in the specified month.
                    dailyWithdrawal:
                      type: array
                      items:
                        type: integer
                      description: Withdrawal per day
                    memberCount:
                      type: integer
                      description: Total number of members at the end of the specified month.
                    avgWithdrawal:
                      type: integer
                      description: Average cannabis withdrawal per member.
        500:
          description: Internal server error occurred
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error occurred"
  /query:
    post:
      summary: Individual Query
      description: Queries the database with arguments specified in the request. Returns 2D-Array structured data. SQL-Injection-Safe.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                queryString:
                  type: string
                  description: Detailed sql to be run on the DB. Injection-Safe
      responses:
        200:
          description: Successful query response with data.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties: {}
                  example:
                    id: "1"
                    name: "John Doe"
        400:
          description: Query lacks sufficient input parameters.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid input parameters"
        500:
          description: Internal server error occured
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error occured"